// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ReactiveGpio")]
[assembly: AssemblyDescriptionAttribute("A library to read and write to GPIO ports on linux using Reactive Extensions")]
[assembly: AssemblyProductAttribute("ReactiveGpio")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright © Neil Stalker 2014")]
[assembly: AssemblyCompanyAttribute("")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
    }
}
